sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '13'
before_script:
- cp tests/helpers/keys.json.example tests/helpers/keys.json
script:
- yarn run cover
- yarn run check-coverage
- yarn run build
after_success:
- yarn run report-coverage
- yarn run semantic-release
branches:
  only:
  - master
env:
  - secure: hj9UDgSHRihLhm7O1g/s70w+UtnL67SWD9RGEXl32meaw/XD2j+AUr7WsD5nC5jKcb2vgEzBaPKWONL2hjJt0nU3h8etfVO6apfXxL2cPT6qzaXjXqz6ETmcTmGPQvUO+DSdXhr/kIoM6gMMQAqTSqAzCiRUW9sXO2s0i2c2UOoP50Yk19evN8TWkGbL6RnCmT5/4q0m0s8mERrLnUGBDHHkOZlclEUrYbKWj9w2/0OJ8X55xpNnoUMjoqX4DiXMVcJ+Y467VntqClZz4MsuWjsiGgsQ94/X0y1MRuRVjGC+iP6jP/fhQ+AZ2ZRosF/n54mQXdu6F2hcQ9vZqrIWhciLkNumfzFNqbCqXs7QP2u99Gjze0AUJt2Hxggh4tcDVijYWthqxNkV/zPUggaL22FrIVNPPtOgltwUYEvTB6IV6stwBfsznp9UszhhGJfDdmjWEV68XCZMYEgqlmr5XZrHaVD91RNSY/kXAkYoPlPREEF22W8OXSyyVYYlgKVEADn2DwKTgSI8EYE57QL5IoStUx5QZ7m49rGbc+FiCrLKqs799zA65zMdpTb6q3b32Tt/GH3/4M844dv2TF2jp2p1hlsqPKkvIUN+XLhu7S2p+Gdij6bI5Jetne2Bji+X1acnPVoRGRG5ppYdy4MdnL93I+zNc+TQH6gB+FP8Rj4=
