sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '13'
before_script:
- cp tests/helpers/keys.json.example tests/helpers/keys.json
script:
- yarn run cover
- yarn run check-coverage
- yarn run build
after_success:
- yarn run report-coverage
- yarn run semantic-release
branches:
  only:
  - master
env:
  global:
  - secure: y2vbpzaPrJCEUsN9Kq7UuTq3cSmH0WvKwcxmnM7C7s5H4THBHrTNead9ykL3eCUssVJWxn6oW0cEop7eN3pNuTY5cm6MZDMR6VESPudCDOx9C0/qpDa//a/VOMEpvUDADduJQVU694G2NTksK6YP83U81v7RF0NizTk9GDkIw3f/7rs75ZemPJZaB5nGZqmz5HVcqn9O9TLEyeH4JFkDx43WJXnEaw01ady3xj6PpTw5JRf8WMNE4bacSBTRue+xrwZLgyTOl1ZSl/0MmhAgp9+RHZjwiEn2+qG7lGn8faxg7ayZIqmn0HfHnwz6waJwLEZhaQTQ9sz0eOjMlN9/o0a59DpcMa4rJZPvPICYi4WfkKUPIXisUjyQInjwQQVSd8FYVHmSdloHh+cUFKv6X2TV13IIimSoZgwrC7L8pCiLm6rCLzZ0tC4W5DGq9iqICBA3vfQxT1/Xn4gB9pNcrD+y+UuYzW1m8M2oI8KNyQPMOicqxcR2jxW74TW1qItL/rhnajTPRYQH7G2u/uCw6rf3QnIBXeN22JxWCkfgpQL+NbuwWIJe5cSYWTNowuhjJzivmUX5NB8i2f0W6Pj0DOydxd53FLkxgQfTrJv6jlU06JwdJnTrU575RS3f4QHb95O3eVYG8qbYyfj+R4+opRbXLWmz60QlKMu9a84IvNg=
  - secure: yA0MgsttUM+LkaIAjtERZIXD8YdftU5l6iqq0760jpIG/lEQg/I1QE51EJLfMu0FYnezemCgH2RjDZ8vyCmWS4Wu5pe8Gz8MUgTCzup4VlpGHc2Af1eL4BE3YnpUaQvL+EMq4rTgHvX2DbuDZQ8JLAJ4X5NDxw8nZDE3innM12jItf1Hp1NjNig0xZi5xKt3KRj1Y7aVMrv7Vo1iyQuZG/QWK/+0MzauWlpGbWzI1/D6JpzozgEoTFSRpcZfHyrg7kd0jYs8RivIW7Pzv0BMrIVkZngLss3WMnpM7q1qAXfCcKK58YRooU2NSfecrq5LZYYaq6hensfOzFSihsHEWOGbzMuiD7+G2KJnR1yRG68CnWkTj8o2wT2RxKxklafD2ki3miHVUYppyKOTiPCkl1hs1w4fkq+34tOKqmsT3eCQ5Vyf6mqNrxSwje2oR0DrP2TqVIuYVQ0cCA8+yhSsxt7vU7Otjd16o/czqpfF/xvnyvPouDy1fVahbk5gwn0tufK+/nOvOntIJOtudkxLe1+8EYiSYu1+7hRnVC9t+VcfxR8cm1bwvzzxUyF2IRsevuZluYwTMs5DEV7pitcmr6GDeRm/qZlxRQk2gF1khZZNiiR2L9Q9QOX+8F5eKAVAAPU3+Eer6P0Mcxak63EVZfFqNdte3kBcWsCrqItoRi0=
  - secure: miJLwilim9paTS/zn3ZmPmWJyoTGoBQiB6ZEDBnEdr/0V40qAHMCZaxKwFltMF6keNNVHLKHaF2ST96Xmpdk9ePhwLnWcX9G2fGwpIdB0YfuVX9RZiXDsbyW4bkZWgdai51yZnShO1ilOncH/0kBX3nyIHiAptobk+vcC/U2sSoBQde283TPsPW0nU1y/JBv502827hW5250YzOTtp9KP/ArtYJPKpXovh1WGWvgiDTEDL/8Qs3dASghCD2Q/DYxLoSj2094Ooao9FPT2QwnsLTIj2kg1ZSHybj4tvlKQNq6U3QHEROfGnBpV1JHukg0tCzZDzhFHU0cRrr3lAcIGWXTXn6/gcAoIraR0by+SLh/GjsR0rkpO6bAc0CPdpGnuzq6cZfmiL8jIfZpKzV/yWaiq8BWvPABefyKjJ33+vzLZwsZfsDc34E/c9NZwnaCcqXNpmylCc6YPtimvsn7OdQG+2IeiS2PjC5l+PKZx0zASn5Yqx6UNDhbipOTCM5tvpGOqMmDqvnNuYGBNDyPCWSfg6kUFJMjUCGgq4wVMtryv08JkdDwwtbu5nxv9zypjYqh79F912mnk0sxG5rUfvLPBoXKtMMc4jXn/cNKVkCjfjQYwc7DcJXJ8v3M5Ph/pL0awhbLBYnPd2WY4EDbadp7ZLOZCuuMKEE28+Yoz3w=
  - secure: coWZAuxmDcjGX1plsdfRwocu9jlmVg8xaiqMvDV2wRRSHTb4ZnPuReUTLgn15oulojVbXZ4pd43gWnASyXncWnheA6vgJItAklVAqYqKdjnO37l0/sDF5sMKPqM7aJXxABd7TRT8y0Px0WJL3HkLGrduVEuAguwTIiRxOPQ3GVtobSaI1hH4RqsIsaQKWRTEpSs4z7Pon2y1+P8Ny7Ng8A6pbFnveFNs7hRhX2biEUuaIxjjiMCRifb/zNf2DEtTUR0HF6GLzDNIyaU/si77GN+72XAoIU6zRgVMePe/lNmiQ4jRhuOjNaK4JVqJfb5TP4peEm98T/pUy0LZ3IvI3GEEvh/YnKLliYNT4oNH4MefGY7laX2WbT/bDNEWJv1xONwspBulU5eGI16CkTmju8HF1ZjuxYLIAEQNFxvTm61KreKaCrPBE7NqjEYrF5nuOHFsrkD1hcU64KWQAyMxqCIvWtCv+eqTnL8pcXV9pT0xV88TV2hLWLW9HqV79z7fVYwD8xHSG5fxsU+lzeVXTLr/1Nu6e7fUbsRfKI2DOqQoHdyktzUTTom86extyt1KCadyQliTB8F/0szWkUulAScoSzfnS9avunWhA7jb7lqNIVCt8cygS8Bdd+2ObUEIEP7Q4wf6C12fiZpH/d/QdogRtOozl1J4gyTioH7A24w=
